# Site settings
title: Brandon To
email: brandon_to@hotmail.com
description: "Personal website of Brandon To"
baseurl: "/"
url: "http://brandonto.github.io"
#twitter_username: SBootstrap
github_username:  brandonto
#facebook_username:  Brandon To

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
