# Site settings
title: Brandon To
email: brandon_to@hotmail.com
description: "Personal website of Brandon To"
baseurl: /
url: "http://brandonto.github.io"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 3
paginate_path: "/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
